import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-50 min-h-screen`}
      >
        <nav className="sticky top-0 z-50 w-full flex justify-between items-center py-4 px-8 bg-gradient-to-r from-red-900 to-red-700 text-white shadow-lg mb-8">
          <div className="flex items-center gap-2 text-2xl font-extrabold tracking-tight">
            <span role="img" aria-label="butcher">🥩</span> Butchery
          </div>
          <div className="flex gap-8 text-lg font-semibold">
when             <a href="/" className="hover:underline underline-offset-4 transition-colors duration-150">Home</a>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
